FROM apache/spark:3.4.1

#seront exécutées en tant qu'utilisateur root
USER root
WORKDIR /app

COPY spark_stream.py .

# Installer dépendances Python
RUN pip install kafka-python

# Préinstaller les jars Kafka pour Spark (au build)
RUN mkdir -p /opt/spark/jars && \
    cd /opt/spark/jars && \
    # Spark-Kafka connector
    curl -L -O https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.4.1/spark-sql-kafka-0-10_2.12-3.4.1.jar && \
    curl -L -O https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.4.1/spark-token-provider-kafka-0-10_2.12-3.4.1.jar && \
    # Kafka clients
    curl -L -O https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.3.2/kafka-clients-3.3.2.jar && \
    # Commons Pool 2 (résout NoClassDefFoundError)
    curl -L -O https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar

# Commande pour lancer Spark Streaming après 60s (attente pour Kafka/Redpanda)
CMD bash -c "sleep 60 && /opt/spark/bin/spark-submit spark_stream.py"